# Generated by Django 5.0.6 on 2024-06-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='craeted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
